-- -*- lua -*-
-- Module file created by spack (https://github.com/spack/spack) on 2024-08-23 09:44:50.977884
--
-- ninja@1.11.1%gcc@13.2.0+re2c build_system=generic arch=linux-rhel8-cascadelake/dckzhme
--

whatis([[Name : ninja]])
whatis([[Version : 1.11.1]])
whatis([[Target : cascadelake]])
whatis([[Short description : Ninja is a small build system with a focus on speed. It differs from other build systems in two major respects: it is designed to have its input files generated by a higher-level build system, and it is designed to run builds as fast as possible.]])

help([[Name   : ninja]])
help([[Version: 1.11.1]])
help([[Target : cascadelake]])
help()
help([[Ninja is a small build system with a focus on speed. It differs from
other build systems in two major respects: it is designed to have its
input files generated by a higher-level build system, and it is designed
to run builds as fast as possible.]])


depends_on("gcc-runtime/13.2.0")
depends_on("glibc/2.28")

prepend_path("PATH", "/appl/spack/v022/install-tree/gcc-13.2.0/ninja-1.11.1-dckzhm/bin", ":")
prepend_path("CMAKE_PREFIX_PATH", "/appl/spack/v022/install-tree/gcc-13.2.0/ninja-1.11.1-dckzhm/.", ":")
prepend_path("PYTHONPATH", "/appl/spack/v022/install-tree/gcc-13.2.0/ninja-1.11.1-dckzhm/misc", ":")

